config/routes.rb
Rails.application.routes.draw do
  root "trips#index"
  devise_for :users, controllers: { registrations: 'registrations' }

  resources :users, only: [:show]

  resources :trips do
    resources :reviews
  end
end

app/models/trip.rb
class Trip < ActiveRecord::Base
  belongs_to :driver, class_name: "User"
  has_many :reviews

  validates :origin, presence: true
  validates :destination, presence: true
  validates :meet_point, presence: true
  validates :rate, presence: true
  validates :car_make, presence: true
  validates :car_model, presence: true
  validates :car_plate, presence: true
  validates :car_plate, presence: true
  validates :avail_cap, presence: true
end

app/controllers/trips_controller.rb
# require_relative "api/mbta.rb"

class TripsController < ApplicationController
  before_action :authorize_user, only: [:destroy]
  # before_action :trip, only: [:show, :edit, :update, :destroy]
  # before_action :review, only: [:show, :edit, :update, :destroy]

  def index
    @trips = Trip.all
    # @mbta = Mbta.new("Red Line")
  end

  def show
    @review = Review.new
    trip_reviews = Review.where(trip_id: trip)
    @reviews = trip_reviews.order(created_at: :desc).page params[:page]
    @rating = @trip.reviews.average(:rating)
    if @rating.nil?
      @rating = "N/A"
    else
      @rating = @rating.round(1)
    end
  end

  def new
    @trip = Trip.new
  end

  def create
    @trip = Trip.new(trip_params)
    @trip.driver_id = current_user.id
    if @trip.save
      flash[:notice] = "Trip successfully created!"
      redirect_to root_path
    else
      flash[:alert] = @trip.errors.full_messages
      render 'new'
    end
  end

  def edit
    trip
  end

  def update
    if trip.update(trip_params)
      flash[:notice] = "You have successfully updated your question!"
      redirect_to trip_path
    else
      flash.now[:notice] = "Invalid input."
      render 'edit'
    end
  end

  def destroy
    if trip.destroy
      flash[:notice] = "You have deleted trip successfully!"
      redirect_to root_path
    else
      flash[:notice] = "You failed to delete trip!"
      render :show
    end
  end

  private

  def trip
    @trip ||= Trip.find(params[:id])
  end

  def trip_params
    params.require(:trip).permit(
      :driver_id,
      :origin,
      :destination,
      :meet_point,
      :rate,
      :car_model,
      :car_make,
      :car_plate,
      :avail_cap
    )
  end
end

app/views/trips/_trip.html.erb
<div class="park-index-list-item">
  <div class="row" data-equalizer>
      <div class="park-info small-6 column" data-equalizer-watch>
          <%= link_to "#{trip.origin}-#{trip.destination}", trip_path(trip) %></br>
          <%= link_to "Driver: #{trip.driver.first_name}", user_path(trip.driver) %></br>
          <%= "Trip rate $#{trip.rate}" %>
      </div>
  </div>
</div>

app/views/trips/edit.html.erb
<div class="review-title small-8 small-centered column text-center">
  <h1 class="review-title">Edit Trip Form</h1>
  <%= render "layouts/trip_form" %>
</div>

app/views/trips/index.html.erb
<h4 class="mbta-header">MBTA Alerts</h4>
<ul></ul>

<% if !@mbta.nil? %>
<div style="border : solid 2px #ff0000; background : #$focus-red; color : #ffffff; padding : 10px; margin-left: 100px; max-width : auto; height : 120px; overflow : auto; ">
  <% @mbta.alert_messages.each do |message| %></li>
    <ul class="mbta">
      <%= message %>
    </ul>
  <% end %>
</div><br />
<% end %>


<%= image_tag("ridesharing.png", :height => 50 ) %>


  <div class="text-center">
    <h2>TRIPS</h2>
  </div>

<% if user_signed_in? %>
<div class="row text-center">
  <div class="small-centered small-2 columns button small">
    <%= link_to "New Trip", new_trip_path, class: "new" %>
  </div>
</div>
<% end %>

<ul class="small-10 small-centered column">
  <%= render @trips %>
</ul>

app/views/trips/new.html.erb
<%if @error_message != nil%>
  <h3><%=@error_message%></h3>
<%end%>

<div class="review-title small-8 small-centered column text-center">
  <h1 class="review-title">New Trip Form</h1>
  <%= render "layouts/trip_form" %>
</div>

app/views/trips/show.html.erb
<div class="review-title small-12 small-centered column text-center">
<div class="trip-table">
  <h2><%= "#{@trip.origin}-#{@trip.destination}" %></h2>
    <h4 class="park-show-location">
  <table align="center">
    <tr>
      <td>Tip rate:</td>
      <td>$ <%= sprintf('%.2f', @trip.rate) %></td>
    </tr>
    <tr>
      <td>Driver:</td>
      <td><%= link_to "#{@trip.driver.first_name} #{@trip.driver.last_name}", user_path(@trip.driver) %></td>
    </tr>
    <tr>
      <td>Meet Point:</td>
      <td><%= @trip.meet_point %></td>
    </tr>
    <tr>
      <td>Driver's Rating:</td>
      <td><%= @trip.driver.rating %></td>
    </tr>

    <% if user_signed_in? %>
      <tr>
        <td>Avaliable seats:</td>
        <td><%= @trip.avail_cap %></td>
      </tr>
      <tr>
        <td>Make</td>
        <td><%= @trip.car_make %></td>
      </tr>
      <tr>
        <td>Model</td>
        <td><%= @trip.car_model %></td>
      </tr>
        <td>Lisence plates</td>
        <td><%= @trip.car_plate %></td>
  <% end %>
</table>
</h4>

  <% if user_signed_in? && ( current_user.id == @trip.driver_id || current_user.role == "admin" ) %>
      <div class="button tiny update-butt">
        <%= button_to 'Edit', edit_trip_path(@trip), method: :get %>
      </div>

    <div class="button tiny update-butt">
      <%= button_to 'Delete', trip_path(@trip), method: "delete"%>
    </div>
  <% end %>
  </div>
  <div>
    <h4 class="small-10 small-centered column">
      Driver Reviews
    </h4>
      <% if user_signed_in? && !@reviews.nil? %>
        <%= render 'reviews/review' %>
      <% else %>
        <%= "No reviews have been posted yet!" %>
      <% end %>
  </div>

  <div>
    <% if user_signed_in? && current_user.id != @trip.driver.id %>
      <div class="review-title small-8 small-centered column text-center">
        <%= render "reviews/form" %>
      </div>
    <% end %>
  </div>
</div>